# Generated by Django 4.0.6 on 2022-08-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_payment_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_index_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('UPI_Vol', models.FloatField()),
                ('UPI_Val', models.FloatField()),
                ('IMPS_Vol', models.FloatField()),
                ('IMPS_Val', models.FloatField()),
                ('NACH_Vol', models.FloatField()),
                ('NACH_Val', models.FloatField()),
                ('NETC_Vol', models.FloatField()),
                ('NETC_Val', models.FloatField()),
                ('NEFT_Vol', models.FloatField()),
                ('NEFT_Val', models.FloatField()),
                ('RTGS_Vol', models.FloatField()),
                ('RTGS_Val', models.FloatField()),
                ('index_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='reference_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_Vol', models.FloatField()),
                ('UPI_Val', models.FloatField()),
                ('IMPS_Vol', models.FloatField()),
                ('IMPS_Val', models.FloatField()),
                ('NACH_Vol', models.FloatField()),
                ('NACH_Val', models.FloatField()),
                ('NETC_Vol', models.FloatField()),
                ('NETC_Val', models.FloatField()),
                ('NEFT_Vol', models.FloatField()),
                ('NEFT_Val', models.FloatField()),
                ('RTGS_Vol', models.FloatField()),
                ('RTGS_Val', models.FloatField()),
                ('p0q0', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='historic_index_data',
            name='date',
            field=models.DateField(),
        ),
    ]
