# Generated by Django 4.0.6 on 2022-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_payment_index', '0002_daily_index_data_reference_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_index_data',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
